#laboratorio de nodes com ansible
#ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|

  (1..2).each do |i|
    # define o sufixo do nome (linha 8) <testando em linha 23>
    config.vm.define "vm#{i}" do |node|
      node.vm.box = "generic/ubuntu2004"
      node.vm.network :private_network,
        :libvirt__network_name => "cavalo",
        #:libvirt__always_destroy => false,
        :ip => "192.168.3.10#{i}"
      node.vm.hostname = "cavalo#{i}"
      node.vm.provision "shell", path: "vm_#{i}.sh"
      node.vm.provision :ansible do |ansible|
        ansible.playbook = "./ym/server.yaml"
        ansible.verbose = "vvv"
      end
      node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
      

      #testando remover o prefixo do nome (nome em linha 8)
      node.vm.provider :libvirt do |libvirt|
        #libvirt.cpus = 2
        #libvirt.memory = 2048
        libvirt.default_prefix = ""
        #libvirt.nested = true
      end


    end
    #config.vm.provision :ansible do |ansible|
    #  ansible.playbook = "./ym/server.yaml"
    #  ansible.verbose = "vvv"
    #end
  end
end
