ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
#ENV['LIBVIRT_DEFAULT_URI'] = 'qemu:///system'
Vagrant.configure("2") do |config|
  
  config.vm.define :ubuntuTest do |cnt|
    # img
    cnt.vm.box = "centos/8"

    # config ansible
    cnt.vm.provision :ansible do |ansible|
      ansible.playbook = "ans.yaml"
      ansible.verbose = "vvv"
    end

    # config provider
    cnt.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 2048
      libvirt.default_prefix = ""
    end

  end
end
