ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

# cluster size
size = 2

Vagrant.configure("2") do |config|

  (2..size).each do |i|

    config.vm.define "suse#{i}" do |node|
      # box configurations
      node.vm.box = "generic/opensuse15"
      node.vm.provider :libvirt do |libvirt|
        libvirt.cpus = 2
        libvirt.memory = 2048
        libvirt.default_prefix = ""
      end

      # custom
      #node.vm.boot_timeout = 300
      #node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"

    end
  end
end
