ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
  
  config.vm.define :OpenSUSE do |opensuse|
    # img
    opensuse.vm.box = "generic/opensuse42"
    opensuse.vm.hostname = "su"
    # config sh
    #opensuse.vm.provision "shell", path: "jenkins.sh"

    # config provider
    opensuse.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 2048
      libvirt.default_prefix = ""
    end

  end
end
