ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
#ENV['LIBVIRT_DEFAULT_URI'] = 'qemu:///system'
Vagrant.configure("2") do |config|
  
  config.vm.define :openSUSE do |opensuse|
    # img
    opensuse.vm.box = "generic/opensuse15"

    # config ansible
    #opensuse.vm.provision :ansible do |ansible|
    #  ansible.playbook = "ans.yaml"
    #  ansible.verbose = "vvv"
    #end

    # config provider
    opensuse.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 2048
      libvirt.default_prefix = ""
    end

  end
end
