# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
  config.vm.define :ubuntuTest22 do |ubt|
    
    # img
    ubt.vm.box = "generic/ubuntu2204"
    ubt.vm.hostname = "ubuntu"
    
    # provider
    ubt.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 2
      #libvirt.memory = 2048
      libvirt.memory = 4096
      libvirt.default_prefix = ""
    end
  end
end

