ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
#ENV['LIBVIRT_DEFAULT_URI'] = 'qemu:///system'

Vagrant.configure("2") do |config|
  config.vm.define :rocky do |rck|
    
    # img
    rck.vm.box = "generic/rocky8"
    rck.vm.hostname = "rocky"

    # config provider
    rck.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 2048
      libvirt.default_prefix = ""
    end

  end
end
