ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
#ENV['LIBVIRT_DEFAULT_URI'] = 'qemu:///system'

Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-server"
  config.vm.hostname = "RDPWindows-server"
  config.vm.provider :libvirt do |libvirt|
    libvirt.default_prefix = "RDPWindows-server"
    libvirt.cpus = 2
    libvirt.memory = 4096
  end
end