# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
#ENV['LIBVIRT_DEFAULT_URI'] = 'qemu:///session'
#ENV['LIBVIRT_DEFAULT_URI'] = 'qemu:///system'

Vagrant.configure("2") do |config|
  config.vm.define :ubuntuTest do |ubt|
    ubt.vm.box = "generic/ubuntu2004"
    ubt.vm.hostname = "ubu"
    ubt.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 2048
      libvirt.default_prefix = ""
      libvirt.nested = true
    end
  end
end
