 # -*- mode: ruby -*-
# vi: set ft=ruby :
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
#ENV['LIBVIRT_DEFAULT_URI'] = 'qemu:///session'
#ENV['LIBVIRT_DEFAULT_URI'] = 'qemu:///system'

Vagrant.configure("2") do |config|
  config.vm.define :ubuntuTest do |ubt|
    ubt.vm.box = "generic/ubuntu2004"
    ubt.vm.hostname = "ubu"
    #ubt.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
    ubt.vm.provision "shell", path: "initial.sh"
    ubt.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 2048
      libvirt.default_prefix = ""
    end
  end
end

# vagrantfile
# ├── vagrant
# │   ├── id_rsa.pub
# │   └── netplan config
# └── vagrant



#30G Infraestrutura
#150G Infraestructure deployment
#3150G Sistemas
