 # -*- mode: ruby -*-
# vi: set ft=ruby :
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|

  (1..3).each do |unit|

    config.vm.define "NodeAnsible#{unit}" do |ubt|
      ubt.vm.box = "generic/ubuntu2004"
      ubt.vm.provision "shell", path: "jota.sh"

      ubt.vm.hostname = "ansible-node-#{unit}"
      ubt.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "~/.ssh/id_ed25519.pub"
      ubt.vm.provider :libvirt do |libvirt|
        libvirt.cpus = 2
        libvirt.memory = 2048
        libvirt.default_prefix = ""
      end
      #ubt.vm.provision :ansible do |ansible|
      #  ansible.playbook = "jota.yaml"
      #  ansible.verbose = "vvv"
      #end
    end

  end #each 
end



## 3

# em um node, run:
# 
# sudo mysql -e "create user backupuser@localhost identified by 'bakp4sswd';"
#
# sudo mysql -e "grant all privileges on *.* to 'backupuser'@'localhost';"
#
# sudo mysql -e "create database teste2;"
#
# systemctl start mariadb
#
#
#




# wsrep_cluster_address=gcomm://192.168.121.55,192.168.121.56,192.168.121.204