 # -*- mode: ruby -*-
# vi: set ft=ruby :
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|

  # senhor de engenho ###################################################
  (1..1).each do |unit|
    config.vm.define "Master" do |ubt|
      ubt.vm.box = "generic/ubuntu2004"
      ubt.vm.provision "shell", path: "jota.sh", args: "unit=#{unit}"
      # rede
      ubt.vm.network :private_network,
        :libvirt__network_name => "mariadb",
        :ip => "192.168.40.#{100 + unit}"
      
      ubt.vm.hostname = "node-master"
      #ubt.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "~/.ssh/id_ed25519.pub"
      ubt.vm.provider :libvirt do |libvirt|
        libvirt.cpus = 2
        libvirt.memory = 2048
        libvirt.default_prefix = ""
      end
      #ubt.vm.provision :ansible do |ansible|
      #  ansible.playbook = "jota.yaml"
      #  ansible.verbose = "vvv"
      #end
    end
  end #each 

  # escravos ############################################################
  (2..3).each do |unit|
    config.vm.define "Node#{unit}" do |ubt|
      ubt.vm.box = "generic/ubuntu2004"
      ubt.vm.provision "shell", path: "pe#{unit}.sh", args: "unit=#{unit}"
      # rede
      ubt.vm.network :private_network,
        :libvirt__network_name => "mariadb",
        :ip => "192.168.40.#{100 + unit}"
      
      ubt.vm.hostname = "node-#{unit}"
      ubt.vm.provider :libvirt do |libvirt|
        libvirt.cpus = 2
        libvirt.memory = 2048
        libvirt.default_prefix = ""
      end
    end
  end #each

end

### 3

# em um node, run:
# 
# sudo mysql -e "create user backupuser@localhost identified by 'bakp4sswd';"
#
# sudo mysql -e "grant all privileges on *.* to 'backupuser'@'localhost';"
#
# sudo mysql -e "create database teste_2;"
#
# sudo mysql -e "show databases;"
#
# systemctl start mariadb

# wsrep_cluster_address=gcomm://192.168.121.55,192.168.121.56,192.168.121.204