# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure("2") do |config|
  config.vm.define :DockerSimple do |doc|
    
    # config box & VM
    doc.vm.box = "generic/ubuntu2404"
    doc.vm.hostname = "docker"
    doc.vm.provision "shell", path: "initial.sh"

    # config provider
    config.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = 2048
      vb.default_prefix = ""
      #vb.nested = true
    end

  end
end
