#laboratorio de nodes com ansible
#ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

# cluster size
size = 3


Vagrant.configure("2") do |config|

  (1..size).each do |i|

    if i == 1
      vm_name = "master"
    elsif i > 1
      vm_name = "node#{i-1}"
    end


    config.vm.define "#{vm_name}" do |node|
      # box configurations
      node.vm.box = "generic/ubuntu2204"
      node.vm.provider :libvirt do |libvirt|
        libvirt.cpus = 1
        libvirt.memory = 1024
        libvirt.default_prefix = ""
      end
      # define network
      node.vm.network :private_network,
        :libvirt__network_name => "dockerswarm",
        :ip => "10.8.0.10#{i}"
      # script running on each vm
      if i > 1
        node.vm.provision "shell", path: "sh/node.sh"
      else
        node.vm.provision "shell", path: "sh/master.sh"
      end

    end
  end
end