# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
#ENV['LIBVIRT_DEFAULT_URI'] = 'qemu:///session'
#ENV['LIBVIRT_DEFAULT_URI'] = 'qemu:///system'

Vagrant.configure("2") do |config|
  config.vm.define :ubuntuGraphic do |ubt|
    ubt.vm.box = "milbuild/graphical-ubuntu16"
    ubt.vm.hostname = "u-graphic"
    ubt.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 2048
      libvirt.default_prefix = ""
      #libvirt.nested = true
    #ubt.vm.provision "shell", path: "jenkins.sh"
    end
  end
end