ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
#ENV['LIBVIRT_DEFAULT_URI'] = 'qemu:///system'
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.provision "shell", inline: <<-SHELL
    apt update -y
    apt upgrade -y
    apt dist-upgrade -y
    apt install -y mariadb-server
    apt install -y postgresql postgresql-contrib
    sudo systemctl start postgresql
    sudo systemctl enable postgresql
  SHELL
end
