ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
#ENV['LIBVIRT_DEFAULT_URI'] = 'qemu:///system'
Vagrant.configure("2") do |config|
  
  config.vm.define :ubuntuTest do |alm|
    alm.vm.box = "generic/alma9"

    # ansible
    alm.vm.provision :ansible do |ansible|
      ansible.playbook = "ans.yaml"
      ansible.verbose = "vvv"
    end

end
