ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'


Vagrant.configure("2") do |config|
  #
  #  vm1 | centos 8
  #
  config.vm.define :vm1 do |cnt|
    cnt.vm.box = "generic/centos8"
    cnt.vm.hostname = "ldap-vm-1"
    cnt.vm.provision :ansible do |ansible|
      ansible.playbook = "update.yaml"
      ansible.verbose = "vvv"
    end
    cnt.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 2048
      libvirt.default_prefix = ""
    end
  end

  #
  #  vm2 | ubuntu 22.04
  #
  config.vm.define :vm2 do |ubt|
    ubt.vm.box = "generic/ubuntu2004"
    ubt.vm.hostname = "ldap-vm-2"
    #ubt.vm.provision "shell", path: "initial.sh"
    ubt.vm.provision :ansible do |ansible|
      ansible.playbook = "update.yaml"
      ansible.verbose = "vvv"
    end
    ubt.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 2048
      libvirt.default_prefix = ""
    end
  end
end


# run on centos

# sudo sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
# sudo sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*