ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
Vagrant.configure("2") do |config|
  config.vm.define "docker" do |docker|	
	  docker.vm.box = "generic/ubuntu2004"
	  docker.vm.network "public_network", bridge: "wlp0s20f3", dev: "wlp0s20f3", ip:"192.168.2.111"
	  docker.vm.provision "shell", path: "command.sh"
  end
  	  
  config.vm.define "ubuntu" do |ubuntu|	
	  ubuntu.vm.box = "generic/ubuntu2004"
	  ubuntu.vm.network "public_network", bridge: "wlp0s20f3", dev: "wlp0s20f3", ip:"192.168.2.112"
	  ubuntu.vm.provision "shell", path: "command2.sh"
  end  
end
