# -*- mode: ruby -*-
# vi: set ft=ruby :
#!/usr/bin/ruby

Vagrant.configure("2") do |config|
  # transformar 4 em variavel
  quantidade = 4

  (1..quantidade).each do |i, vm_name|
    # define o sufixo do nome (linha 8) <testando em linha 23>

    # seleciona o nome com base no numero do node
    if i == 1
      vm_name = "master"

    elsif i > 1 and i < quantidade
      vm_name = "node-#{i-1}"

    elsif i == quantidade
      vm_name = "proxy"
    end
    #puts i
    #puts vm_name
    config.vm.define "#{vm_name}" do |node|
      node.vm.box = "generic/ubuntu2004"
      node.vm.network :private_network,
        :libvirt__network_name => "cavalo",
        #:libvirt__always_destroy => false,
        :ip => "192.168.3.#{100 + i}"
      node.vm.hostname = "horse-#{vm_name}"
      node.vm.provision "shell", path: "sh/vm_#{vm_name}.sh"
      
      node.vm.provision :ansible do |ansible|
        ansible.playbook = "./yml/install.yaml"
        ansible.verbose = "vvv"
      end
      ## ou rode 'vagrant provision --provision-with ansible'
      node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
      
      #testando remover o prefixo do nome (nome em linha 8)
      node.vm.provider :libvirt do |libvirt|
        libvirt.cpus = 1
        libvirt.memory = 1024
        libvirt.default_prefix = ""
        libvirt.nested = true
      end
    end

  end
end