ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
#ENV['LIBVIRT_DEFAULT_URI'] = 'qemu:///system'

Vagrant.configure("2") do |config|
  config.vm.box = "peru/windows-10-enterprise-x64-eval"
  config.vm.hostname = "RDPWindows"
  config.vm.provider :libvirt do |libvirt|
    libvirt.default_prefix = "RDPWindows"
    libvirt.cpus = 2
    libvirt.memory = 4096
  end
end
