# -*- mode: ruby -*-
# vi: set ft=ruby :
#!/usr/bin/ruby

Vagrant.configure("2") do |config|
  # transformar 4 em variavel
  quantidade = 4

  (1..quantidade).each do |i, vm_name|

    config.vm.define "#{vm_name}" do |node|
      node.vm.box = "generic/ubuntu2004"
      node.vm.hostname = "horse-#{vm_name}"
      node.vm.provision "shell", path: "sh/vm_#{vm_name}.sh"
      node.vm.provision :ansible do |ansible|
       ansible.playbook = "./yml/install.yaml"
       ansible.verbose = "vvv"
      end
      ## ou rode 'vagrant provision --provision-with ansible'
      node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"

      #testando remover o prefixo do nome (nome em linha 8)
      node.vm.provider :libvirt do |libvirt|
        libvirt.cpus = 2
        libvirt.memory = 1024
        libvirt.default_prefix = ""
        libvirt.nested = true
      end
    end

  end
end