#laboratorio de nodes com ansible
#ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

# cluster size
size = 3

Vagrant.configure("2") do |config|

  (1..size).each do |i|

    config.vm.define "vm_ubuntu#{i}" do |node|
      # box configurations
      node.vm.box = "generic/ubuntu2204"
      node.vm.provider :libvirt do |libvirt|
        libvirt.cpus = 1
        libvirt.memory = 1024
        #libvirt.memory = 2048
        libvirt.default_prefix = ""
      end
    end
  end
end
